version: '3.8'

services:
  web:
    build: .
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=sqlite:///database.db
      - DATABASE_TEST_URL=sqlite:///test_database.db
      - SECRET_KEY=myjwtsecret
      - ALGORITHM=HS256